version: "3"

services:
  app:
    build:
      context: .
      dockerfile: local.Dockerfile
      args:
        VARIANT: "3.10"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - .:/workspace:cached
      - ~/.kube/config:/home/vscode/.kube/config

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    user: vscode

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      PGPASSWORD: postgres
      EMAIL_URL: smtp://mailhog:1025
      PRE_COMMIT_HOME: "/workspace/.cache/pre-commit"
      TELEGRAM_API_ID:
      TELEGRAM_API_HASH:
      TELEGRAM_BASE_USERS:
      TELEGRAM_STRING_SESSION:
      DJANGO_SETTINGS_MODULE: "emt.settings"

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8025:8025

volumes:
  postgres-data:
