# Generated by Django 4.0.3 on 2022-03-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('employees', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='providers.resource'),
        ),
        migrations.AddField(
            model_name='permission',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='given_permissions', to='groups.group'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('source', 'resource', 'employee')},
        ),
    ]
