# Generated by Django 4.0.3 on 2022-03-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='os',
        ),
    ]
