# Generated by Django 4.0.3 on 2022-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
