# Generated by Django 4.0.3 on 2022-12-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gitlab_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
