# Generated by Django 4.1.4 on 2022-12-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_employee_gitlab_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="discord_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
