# Generated by Django 4.1.4 on 2022-12-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employee_discord_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="discord_username",
            new_name="discord_id",
        ),
    ]
