apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports: {{- toYaml .Values.service.ports | nindent 4 }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
