global:
  backend:
    env:
      DJANGO_SECRET_KEY: ""
      DJANGO_ALLOWED_HOSTS: "emt.sparklingtide.dev"

      DATABASE_URL: postgres://emt:emt@backend-postgresql:5432/emt

web:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
    tls:
      - hosts:
          - emt.sparklingtide.dev
        secretName: emt-tls
    hosts:
      - host: emt.sparklingtide.dev
        paths:
        - /api
        - /static
