# Generated by Django 4.0.3 on 2022-03-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='resources',
            field=models.ManyToManyField(related_name='+', to='providers.resource'),
        ),
    ]
