# Generated by Django 4.0.3 on 2022-03-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResource',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.resource')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('providers.resource',),
        ),
        migrations.CreateModel(
            name='TestResourceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employee')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='testprovider.testresource')),
            ],
            options={
                'unique_together': {('resource', 'employee')},
            },
        ),
    ]
