# Generated by Django 4.0.3 on 2022-03-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenVPN',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.resource')),
                ('openvpn_host', models.CharField(max_length=100)),
                ('openvpn_port', models.PositiveIntegerField(default=1194)),
                ('vault_url', models.CharField(max_length=100)),
                ('vault_approle_role_id', models.CharField(max_length=100)),
                ('vault_approle_secret_id', models.CharField(max_length=100)),
                ('vault_pki_role_name', models.CharField(default='client', max_length=100)),
                ('vault_pki_mount_point', models.CharField(default='pki', max_length=100)),
                ('vault_kv_mount_point', models.CharField(default='kv', max_length=100)),
                ('ta_key', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('providers.resource',),
        ),
        migrations.CreateModel(
            name='OpenVPNClient',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.resource')),
                ('common_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('certificate', models.TextField()),
                ('private_key', models.TextField()),
                ('issuing_ca', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('vpn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='openvpn_vault.openvpn')),
            ],
            options={
                'unique_together': {('vpn', 'employee')},
            },
            bases=('providers.resource',),
        ),
    ]
