# Generated by Django 4.0.3 on 2022-03-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn_vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openvpnclient',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='openvpnclient',
            name='issuing_ca',
        ),
        migrations.RemoveField(
            model_name='openvpnclient',
            name='private_key',
        ),
    ]
