# Generated by Django 4.0.3 on 2022-12-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gitlab',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.resource')),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('role', models.IntegerField(choices=[(5, 'Minimal Access'), (10, 'Guest'), (20, 'Reporter'), (30, 'Developer'), (40, 'Maintainer'), (50, 'Owner')], default=5)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('providers.resource',),
        ),
    ]
