apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "migrations.jobname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- include "backend.renderPullSecrets" . | nindent 6 }}
      containers:
      - name: {{ include "common.names.fullname" . }}
        image: {{ include "backend.image" . }}
        imagePullPolicy: {{ include "backend.imagePullPolicy" . }}
        {{- if .Values.command }}
        command:
        {{- range .Values.command }}
          - {{ . | quote }}
        {{- end }}
        {{- end }}
        {{- include "backend.renderEnv" . | nindent 8 }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
