apiVersion: v2
name: backend
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
- name: common
  version: 1.*.*
  repository: https://charts.bitnami.com/bitnami
- name: postgresql
  version: 11.0.2
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
